apiVersion: v1
kind: Pod
metadata:
  name: prez-k8s-pod-unhealthy
spec:
  containers:
  - name: prez-k8s-container-unhealthy
    image: luksa/kubia-unhealthy
    ports:
      - containerPort: 8080
        protocol: TCP
    resources:
      requests:
        cpu: 0.1
        memory: 16Mi
      limits:
        cpu: 0.5
        memory: 128Mi
#    livenessProbe:
#      httpGet:
#        path: /
#        port: 8080
#      initialDelaySeconds: 5
#      periodSeconds: 3
