apiVersion: v1
kind: Pod
metadata:
  name: prez-k8s-pod-with-disk
spec:
  volumes:
    - name: mongodb-data
      azureDisk:
        kind: Managed
        diskName: prez-k8s-static-disk
        diskURI: /subscriptions/4aea99db-397a-45e5-a508-e6e06db77164/resourceGroups/MC_prez-k8s-rg_prez-k8s_eastus/providers/Microsoft.Compute/disks/prez-k8s-static-disk
  containers:
    - image: mongo
      name: mongodb
      volumeMounts:
      - name: mongodb-data
        mountPath: /data/db