apiVersion: v1
kind: Pod
metadata:
  name: prez-k8s-pod-with-dyn-pvc
spec:
  containers:
    - name: prez-k8s-dyn-pvc
      image: luksa/kubia
      volumeMounts:
        - name: prez-k8s-data
          mountPath: /data
  volumes:
    - name: prez-k8s-data
      persistentVolumeClaim:
        claimName: prez-k8s-dyn-pvc